name: ci

on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          lfs: true
          fetch-depth: 0

      - name: install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev libxslt-dev libxml2-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: build
        run: |
          export LANG=en_US.UTF-8
          export JEKYLL_ENV=production
          bundle install
          bundle exec jekyll build --future --profile --trace  --verbose
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

